"""Reusable finding detail panel: evidence + optional response diff."""
from __future__ import annotations

from textual.app import ComposeResult
from textual.containers import Horizontal, Vertical
from textual.widgets import Button, Static, TextArea, TabbedContent, TabPane

_PRIORITY_KEYS = [
    "verdict", "confidence", "score", "severity",
    "category", "attack", "test_kind",
    "url", "endpoint", "method",
    "evidence", "payload", "injected", "probe", "signals",
    "bypass_source", "original_status", "new_status",
    "source", "sink",
]


def _finding_summary(f: dict) -> str:
    lines = []
    shown: set[str] = set()

    for key in _PRIORITY_KEYS:
        if key in f:
            val = f[key]
            if isinstance(val, list):
                val = ", ".join(str(v) for v in val)
            lines.append(f"{key}: {val}")
            shown.add(key)

    extras = [
        (k, v) for k, v in f.items()
        if k not in shown and not k.startswith("_")
    ]
    if extras:
        lines.append("")
        lines.append("--- additional ---")
        for k, v in extras:
            if isinstance(v, list):
                v = ", ".join(str(x) for x in v)
            lines.append(f"{k}: {v}")

    return "\n".join(lines)


class FindingDetail(Vertical):
    """Shows evidence, request snippets, and optional A/B diff for a finding."""

    DEFAULT_CSS = """
    FindingDetail {
        height: 1fr;
    }
    FindingDetail TextArea {
        height: 1fr;
        border: none;
    }
    FindingDetail #brief-action-bar {
        height: 3;
        padding: 0 1;
        background: $surface-darken-1;
    }
    FindingDetail #brief-action-bar Button {
        min-width: 18;
        margin-right: 1;
    }
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._current: dict | None = None

    def compose(self) -> ComposeResult:
        with TabbedContent():
            with TabPane("Evidence", id="tab-evidence"):
                yield TextArea("", id="evidence-text", read_only=True)
            with TabPane("Diff", id="tab-diff"):
                yield TextArea("", id="diff-text", read_only=True)
            with TabPane("AI Briefing", id="tab-briefing"):
                with Horizontal(id="brief-action-bar"):
                    yield Button("Brief this finding", id="btn-brief", variant="primary")
                yield TextArea("", id="briefing-text", read_only=True)
            with TabPane("Raw", id="tab-raw"):
                yield TextArea("", id="raw-text", read_only=True)

    def show_finding(self, f: dict) -> None:
        self._current = f
        summary = _finding_summary(f)
        evidence = f.get("evidence", "")
        full_evidence = f"{summary}\n\nevidence:\n{evidence}" if evidence and evidence not in summary else summary
        self.query_one("#evidence-text", TextArea).load_text(full_evidence)

        resp_a = f.get("response_a", "")
        resp_b = f.get("response_b", "")
        if resp_a or resp_b:
            diff = f"--- Response A ---\n{resp_a}\n\n--- Response B ---\n{resp_b}"
        else:
            diff = "(no diff available)"
        self.query_one("#diff-text", TextArea).load_text(diff)

        self.query_one("#briefing-text", TextArea).load_text(_format_briefing(f.get("_briefing")))

        self.query_one("#raw-text", TextArea).load_text(
            "\n".join(f"{k}: {v}" for k, v in f.items() if not k.startswith("_"))
        )


    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "btn-brief":
            self._kick_brief()

    def _kick_brief(self) -> None:
        if not self._current:
            self.app.notify("No finding selected.", severity="warning", timeout=4)
            return
        finding = self._current
        target = ""
        try:
            target = self.app._state.target or ""  # type: ignore[attr-defined]
        except Exception:
            pass
        self.query_one("#briefing-text", TextArea).load_text(
            "Briefing in progress — calling LLM…"
        )
        self.app.notify("Briefing started — see Findings tab when complete.", timeout=3)
        worker_fn = getattr(self.app, "_run_quick_brief", None)
        if worker_fn is None:
            self.query_one("#briefing-text", TextArea).load_text(
                "App is missing _run_quick_brief — wire the worker on HxxpsinApp."
            )
            return
        worker_fn(finding, target)


def _format_briefing(br) -> str:
    if not isinstance(br, dict):
        return (
            "(no AI briefing for this finding)\n\n"
            "Briefings are generated by the challenge solver during a full scan,\n"
            "or on demand via the [B]rief button (when implemented)."
        )
    lines: list[str] = []
    hyp = br.get("preliminary_hypothesis", "inconclusive")
    conf = br.get("confidence", 0)
    lines.append(f"hypothesis: {hyp}    confidence: {conf}/3")
    base = br.get("baseline_behavior", "")
    if base:
        lines.append(f"baseline:   {base}")
    reasoning = br.get("reasoning", "")
    if reasoning:
        lines.append("")
        lines.append("--- reasoning ---")
        lines.append(reasoning)
    for label, key in [
        ("key observations", "key_observations"),
        ("evidence FOR", "evidence_for"),
        ("evidence AGAINST", "evidence_against"),
        ("missing information", "missing_information"),
    ]:
        items = br.get(key) or []
        if not items:
            continue
        lines.append("")
        lines.append(f"--- {label} ---")
        for it in items:
            lines.append(f"  • {it}")
    err = br.get("error", "")
    if err:
        lines.append("")
        lines.append(f"error: {err}")
    elapsed = br.get("elapsed_ms", 0)
    in_tok = br.get("input_tokens", 0)
    out_tok = br.get("output_tokens", 0)
    if elapsed or in_tok or out_tok:
        lines.append("")
        lines.append(f"[{elapsed}ms — in:{in_tok}tok / out:{out_tok}tok]")
    return "\n".join(lines)
